package main

import "core:fmt"
import "core:strings"
import alicorn "../../runtime"

// theme_cli_codegen_odin emits a source file with a factory procedure rather
// than an initialized package global. Style_Theme contains owned slices, so
// each call must allocate storage that is later released with the generated
// destroy procedure (or after style_theme_register copies it).
theme_cli_codegen_odin :: proc(
	value: alicorn.Style_Theme,
	materials: []alicorn.Style_Material_Definition,
	symbol, package_name, runtime_import: string,
) -> (generated: string, ok: bool) {
	if !theme_cli_codegen_identifier_is_valid(symbol) ||
	   !theme_cli_codegen_identifier_is_valid(package_name) ||
	   !theme_cli_codegen_import_is_valid(runtime_import) {
		return "", false
	}

	builder, builder_error := strings.builder_make_none()
	if builder_error != nil { return "", false }
	defer strings.builder_destroy(&builder)

	fmt.sbprintln(&builder, "// Generated by `alicorn theme compile`; do not edit.")
	fmt.sbprintfln(&builder, "package {:s}", package_name)
	fmt.sbprintln(&builder, "")
	fmt.sbprintfln(&builder, "import alicorn \"{:s}\"", runtime_import)
	fmt.sbprintln(&builder, "")
	fmt.sbprintfln(&builder, "// Returns owned token/binding slices. Call {:s}_destroy after registration.", symbol)
	fmt.sbprintfln(&builder, "{:s} :: proc(allocator := context.allocator) -> alicorn.Style_Theme {{", symbol)
	fmt.sbprintln(&builder, "    result := alicorn.DEFAULT_STYLE_THEME")
	fmt.sbprintln(&builder, "    result.colors = {")
	for color in value.colors {
		fmt.sbprint(&builder, "        alicorn.Color{")
		fmt.sbprintf(&builder, "{:.9g}, {:.9g}, {:.9g}, {:.9g}", color.r, color.g, color.b, color.a)
		fmt.sbprintln(&builder, "},")
	}
	fmt.sbprintln(&builder, "    }")

	fmt.sbprintfln(&builder, "    result.color_tokens = make([]alicorn.Color, %d, allocator)", len(value.color_tokens))
	for color, index in value.color_tokens {
		fmt.sbprintf(&builder, "    result.color_tokens[{:d}] = alicorn.Color{{", index)
		fmt.sbprintf(&builder, "{:.9g}, {:.9g}, {:.9g}, {:.9g}", color.r, color.g, color.b, color.a)
		fmt.sbprintln(&builder, "}")
	}
	fmt.sbprintln(&builder, "    result.core_color_tokens = {")
	for token in value.core_color_tokens {
		fmt.sbprintfln(&builder, "        alicorn.Style_Color_Token_ID({:d}),", u32(token))
	}
	fmt.sbprintln(&builder, "    }")

	fmt.sbprintfln(&builder, "    result.length_tokens = make([]alicorn.Style_Length, %d, allocator)", len(value.length_tokens))
	for length, index in value.length_tokens {
		fmt.sbprintf(&builder, "    result.length_tokens[{:d}] = alicorn.Style_Length{{logical_units=", index)
		fmt.sbprintf(&builder, "{:.9g}", length.logical_units)
		fmt.sbprintln(&builder, "}")
	}
	fmt.sbprintfln(&builder, "    result.extension_color_roles = make([]alicorn.Style_Extension_Color_Role_Binding, %d, allocator)", len(value.extension_color_roles))
	for binding, index in value.extension_color_roles {
		fmt.sbprintfln(&builder, "    result.extension_color_roles[{:d}] = alicorn.Style_Extension_Color_Role_Binding{{", index)
		fmt.sbprintfln(&builder, "        role=alicorn.Style_Extension_Color_Role_ID(u64({:d})),", u64(binding.role))
		fmt.sbprintfln(&builder, "        token=alicorn.Style_Color_Token_ID({:d}),", u32(binding.token))
		fmt.sbprintln(&builder, "    }")
	}
	fmt.sbprintfln(&builder, "    result.extension_length_roles = make([]alicorn.Style_Extension_Length_Role_Binding, %d, allocator)", len(value.extension_length_roles))
	for binding, index in value.extension_length_roles {
		fmt.sbprintfln(&builder, "    result.extension_length_roles[{:d}] = alicorn.Style_Extension_Length_Role_Binding{{", index)
		fmt.sbprintfln(&builder, "        role=alicorn.Style_Extension_Length_Role_ID(u64({:d})),", u64(binding.role))
		fmt.sbprintfln(&builder, "        token=alicorn.Style_Length_Token_ID({:d}),", u32(binding.token))
		fmt.sbprintln(&builder, "    }")
	}
	fmt.sbprintfln(&builder, "    result.color_token_provenance = make([]alicorn.Style_Token_Provenance, %d, allocator)", len(value.color_token_provenance))
	for provenance, index in value.color_token_provenance {
		fmt.sbprintf(&builder, "    result.color_token_provenance[%d] = alicorn.Style_Token_Provenance{{id=%d, name=%q, alias_target=%q}}\n", index, provenance.id, provenance.name, provenance.alias_target)
	}
	fmt.sbprintfln(&builder, "    result.length_token_provenance = make([]alicorn.Style_Token_Provenance, %d, allocator)", len(value.length_token_provenance))
	for provenance, index in value.length_token_provenance {
		fmt.sbprintf(&builder, "    result.length_token_provenance[%d] = alicorn.Style_Token_Provenance{{id=%d, name=%q, alias_target=%q}}\n", index, provenance.id, provenance.name, provenance.alias_target)
	}
	fmt.sbprintfln(&builder, "    result.extension_color_role_provenance = make([]alicorn.Style_Extension_Color_Role_Provenance, %d, allocator)", len(value.extension_color_role_provenance))
	for provenance, index in value.extension_color_role_provenance {
		fmt.sbprintf(&builder, "    result.extension_color_role_provenance[%d] = alicorn.Style_Extension_Color_Role_Provenance{{role=alicorn.Style_Extension_Color_Role_ID(u64(%d)), name=%q}}\n", index, u64(provenance.role), provenance.name)
	}
	fmt.sbprintfln(&builder, "    result.extension_length_role_provenance = make([]alicorn.Style_Extension_Length_Role_Provenance, %d, allocator)", len(value.extension_length_role_provenance))
	for provenance, index in value.extension_length_role_provenance {
		fmt.sbprintf(&builder, "    result.extension_length_role_provenance[%d] = alicorn.Style_Extension_Length_Role_Provenance{{role=alicorn.Style_Extension_Length_Role_ID(u64(%d)), name=%q}}\n", index, u64(provenance.role), provenance.name)
	}
	theme_cli_codegen_emit_button_recipe_diffs(&builder, value.button_recipes)
	fmt.sbprintln(&builder, "    return result")
	fmt.sbprintln(&builder, "}")
	fmt.sbprintln(&builder, "")
	fmt.sbprintfln(&builder, "{:s}_materials :: [{:d}]alicorn.Style_Material_Definition{{", symbol, len(materials))
	for definition in materials {
		material := definition.material
		kind := ".Analytic_Relief"
		if material.kind == .Flat { kind = ".Flat" }
		fmt.sbprintln(&builder, "    alicorn.Style_Material_Definition{")
		fmt.sbprintfln(&builder, "        name={:q},", definition.name)
		fmt.sbprintfln(&builder, "        material=alicorn.Style_Material{{kind={:s},", kind)
		fmt.sbprintfln(&builder, "            bevel_width={:.9g}, bevel_strength={:.9g},", material.bevel_width, material.bevel_strength)
		fmt.sbprintfln(&builder, "            inner_shadow_strength={:.9g}, outer_shadow_strength={:.9g},", material.inner_shadow_strength, material.outer_shadow_strength)
		fmt.sbprintfln(&builder, "            outer_shadow_radius={:.9g},", material.outer_shadow_radius)
		fmt.sbprintln(&builder, "        },")
		fmt.sbprintln(&builder, "    },")
	}
	fmt.sbprintln(&builder, "}")
	fmt.sbprintln(&builder, "")
	fmt.sbprintfln(&builder, "{:s}_destroy :: proc(value: ^alicorn.Style_Theme, allocator := context.allocator) {{", symbol)
	fmt.sbprintln(&builder, "    if value == nil { return }")
	fmt.sbprintln(&builder, "    // Provenance strings are static generated literals; only their slices are owned.")
	fmt.sbprintln(&builder, "    delete(value.color_tokens, allocator)")
	fmt.sbprintln(&builder, "    delete(value.length_tokens, allocator)")
	fmt.sbprintln(&builder, "    delete(value.extension_color_roles, allocator)")
	fmt.sbprintln(&builder, "    delete(value.extension_length_roles, allocator)")
	fmt.sbprintln(&builder, "    delete(value.color_token_provenance, allocator)")
	fmt.sbprintln(&builder, "    delete(value.length_token_provenance, allocator)")
	fmt.sbprintln(&builder, "    delete(value.extension_color_role_provenance, allocator)")
	fmt.sbprintln(&builder, "    delete(value.extension_length_role_provenance, allocator)")
	fmt.sbprintln(&builder, "    value.color_tokens = nil")
	fmt.sbprintln(&builder, "    value.length_tokens = nil")
	fmt.sbprintln(&builder, "    value.extension_color_roles = nil")
	fmt.sbprintln(&builder, "    value.extension_length_roles = nil")
	fmt.sbprintln(&builder, "    value.color_token_provenance = nil")
	fmt.sbprintln(&builder, "    value.length_token_provenance = nil")
	fmt.sbprintln(&builder, "    value.extension_color_role_provenance = nil")
	fmt.sbprintln(&builder, "    value.extension_length_role_provenance = nil")
	fmt.sbprintln(&builder, "}")

	cloned, builder_clone_error := strings.clone(strings.to_string(builder))
	if builder_clone_error != nil { return "", false }
	generated = cloned
	return generated, true
}

theme_cli_codegen_emit_button_recipe_diffs :: proc(builder: ^strings.Builder, recipes: alicorn.Button_Recipe_Set) {
	defaults := alicorn.DEFAULT_STYLE_THEME.button_recipes
	for index in 0..<alicorn.BUTTON_VARIANT_COUNT {
		current := recipes.recipes[index]
		base := defaults.recipes[index]
		prefix := fmt.tprintf("    result.button_recipes.recipes[{:d}]", index)
		if current.surface_role != base.surface_role { fmt.sbprintfln(builder, "{:s}.surface_role = {:s}", prefix, theme_cli_codegen_role(current.surface_role)) }
		if current.text_role != base.text_role { fmt.sbprintfln(builder, "{:s}.text_role = {:s}", prefix, theme_cli_codegen_role(current.text_role)) }
		if current.surface_visible != base.surface_visible { fmt.sbprintfln(builder, "{:s}.surface_visible = {:s}", prefix, theme_cli_codegen_bool(current.surface_visible)) }
		if current.selected_indicator != base.selected_indicator {
			indicator := ".None"
			if current.selected_indicator == .Underline { indicator = ".Underline" }
			fmt.sbprintfln(builder, "{:s}.selected_indicator = {:s}", prefix, indicator)
		}
		if current.selected_indicator_role != base.selected_indicator_role { fmt.sbprintfln(builder, "{:s}.selected_indicator_role = {:s}", prefix, theme_cli_codegen_role(current.selected_indicator_role)) }
		if current.focus_indicator_mode != base.focus_indicator_mode {
			mode := ".Always"
			if current.focus_indicator_mode == .Keyboard_Only { mode = ".Keyboard_Only" }
			fmt.sbprintfln(builder, "{:s}.focus_indicator_mode = {:s}", prefix, mode)
		}
		if current.focus_role != base.focus_role { fmt.sbprintfln(builder, "{:s}.focus_role = {:s}", prefix, theme_cli_codegen_role(current.focus_role)) }
		if current.semantic_active_role != base.semantic_active_role { fmt.sbprintfln(builder, "{:s}.semantic_active_role = {:s}", prefix, theme_cli_codegen_role(current.semantic_active_role)) }
		theme_cli_codegen_emit_transform_diff(builder, fmt.tprintf("{:s}.selected", prefix), current.selected, base.selected)
		theme_cli_codegen_emit_transform_diff(builder, fmt.tprintf("{:s}.hovered", prefix), current.hovered, base.hovered)
		theme_cli_codegen_emit_transform_diff(builder, fmt.tprintf("{:s}.pressed", prefix), current.pressed, base.pressed)
		theme_cli_codegen_emit_transform_diff(builder, fmt.tprintf("{:s}.disabled", prefix), current.disabled, base.disabled)
	}
}

theme_cli_codegen_emit_transform_diff :: proc(
	builder: ^strings.Builder,
	prefix: string,
	current, base: alicorn.Style_Transform,
) {
	if current.surface_role != base.surface_role { fmt.sbprintfln(builder, "{:s}.surface_role = {:s}", prefix, theme_cli_codegen_role(current.surface_role)) }
	if current.surface_mix != base.surface_mix { fmt.sbprintfln(builder, "{:s}.surface_mix = {:.9g}", prefix, current.surface_mix) }
	if current.text_role != base.text_role { fmt.sbprintfln(builder, "{:s}.text_role = {:s}", prefix, theme_cli_codegen_role(current.text_role)) }
	if current.text_mix != base.text_mix { fmt.sbprintfln(builder, "{:s}.text_mix = {:.9g}", prefix, current.text_mix) }
}

theme_cli_codegen_role :: proc(role: alicorn.Style_Color_Role) -> string {
	switch role {
	case .Window_Background: return "alicorn.Style_Color_Role.Window_Background"
	case .Surface: return "alicorn.Style_Color_Role.Surface"
	case .Subtle_Surface: return "alicorn.Style_Color_Role.Subtle_Surface"
	case .Editor_Background: return "alicorn.Style_Color_Role.Editor_Background"
	case .Text: return "alicorn.Style_Color_Role.Text"
	case .Muted_Text: return "alicorn.Style_Color_Role.Muted_Text"
	case .Accent: return "alicorn.Style_Color_Role.Accent"
	case .Accent_Hover: return "alicorn.Style_Color_Role.Accent_Hover"
	case .Accent_Pressed: return "alicorn.Style_Color_Role.Accent_Pressed"
	case .Accent_Text: return "alicorn.Style_Color_Role.Accent_Text"
	case .Selection: return "alicorn.Style_Color_Role.Selection"
	case .Focus: return "alicorn.Style_Color_Role.Focus"
	case .Semantic_Focus: return "alicorn.Style_Color_Role.Semantic_Focus"
	case .Border: return "alicorn.Style_Color_Role.Border"
	case .Danger: return "alicorn.Style_Color_Role.Danger"
	case .Success: return "alicorn.Style_Color_Role.Success"
	case .Scrollbar_Track: return "alicorn.Style_Color_Role.Scrollbar_Track"
	case .Scrollbar_Thumb: return "alicorn.Style_Color_Role.Scrollbar_Thumb"
	case .Count:
	}
	return "alicorn.Style_Color_Role.Text"
}

theme_cli_codegen_bool :: proc(value: bool) -> string {
	if value { return "true" }
	return "false"
}

theme_cli_codegen_identifier_is_valid :: proc(value: string) -> bool {
	if len(value) == 0 { return false }
	switch value {
	case "assert", "bit_field", "bit_set", "break", "case", "cast", "const",
	     "continue", "defer", "distinct", "do", "dynamic", "else", "enum",
	     "fallthrough", "false", "for", "foreign", "if", "import", "in",
	     "inline", "map", "maybe", "or_else", "or_return", "package", "proc",
	     "return", "select", "struct", "switch", "true", "typeid", "union",
	     "using", "when", "where", "while":
		return false
	}
	for index := 0; index < len(value); index += 1 {
		character := value[index]
		letter := character >= 'a' && character <= 'z' || character >= 'A' && character <= 'Z'
		if index == 0 {
			if !letter && character != '_' { return false }
		} else if !letter && (character < '0' || character > '9') && character != '_' {
			return false
		}
	}
	return true
}

// Odin import paths are emitted inside a quoted string. This intentionally
// accepts ordinary module/relative paths only, so the CLI never emits an
// unexpected escape or source fragment.
theme_cli_codegen_import_is_valid :: proc(value: string) -> bool {
	if len(value) == 0 { return false }
	for index := 0; index < len(value); index += 1 {
		character := value[index]
		letter := character >= 'a' && character <= 'z' || character >= 'A' && character <= 'Z'
		digit := character >= '0' && character <= '9'
		if !letter && !digit && character != '_' && character != '-' &&
		   character != '.' && character != '/' && character != ':' {
			return false
		}
	}
	return true
}
