package main

import "core:fmt"
import "core:strings"
import alicorn "../../runtime"

// theme_cli_codegen_odin emits a source file with a factory procedure rather
// than an initialized package global. Style_Theme contains owned slices, so
// each call must allocate storage that is later released with the generated
// destroy procedure (or after style_theme_register copies it).
theme_cli_codegen_odin :: proc(
	value: alicorn.Style_Theme,
	symbol, package_name, runtime_import: string,
) -> (generated: string, ok: bool) {
	if !theme_cli_codegen_identifier_is_valid(symbol) ||
	   !theme_cli_codegen_identifier_is_valid(package_name) ||
	   !theme_cli_codegen_import_is_valid(runtime_import) {
		return "", false
	}

	builder, builder_error := strings.builder_make_none()
	if builder_error != nil { return "", false }
	defer strings.builder_destroy(&builder)

	fmt.sbprintln(&builder, "// Generated by `alicorn theme compile`; do not edit.")
	fmt.sbprintfln(&builder, "package {:s}", package_name)
	fmt.sbprintln(&builder, "")
	fmt.sbprintfln(&builder, "import alicorn \"{:s}\"", runtime_import)
	fmt.sbprintln(&builder, "")
	fmt.sbprintfln(&builder, "// Returns owned token/binding slices. Call {:s}_destroy after registration.", symbol)
	fmt.sbprintfln(&builder, "{:s} :: proc(allocator := context.allocator) -> alicorn.Style_Theme {{", symbol)
	fmt.sbprintln(&builder, "    result := alicorn.DEFAULT_STYLE_THEME")
	fmt.sbprintln(&builder, "    result.colors = {")
	for color in value.colors {
		fmt.sbprint(&builder, "        alicorn.Color{")
		fmt.sbprintf(&builder, "{:.9g}, {:.9g}, {:.9g}, {:.9g}", color.r, color.g, color.b, color.a)
		fmt.sbprintln(&builder, "},")
	}
	fmt.sbprintln(&builder, "    }")

	fmt.sbprintfln(&builder, "    result.color_tokens = make([]alicorn.Color, %d, allocator)", len(value.color_tokens))
	for color, index in value.color_tokens {
		fmt.sbprintf(&builder, "    result.color_tokens[{:d}] = alicorn.Color{{", index)
		fmt.sbprintf(&builder, "{:.9g}, {:.9g}, {:.9g}, {:.9g}", color.r, color.g, color.b, color.a)
		fmt.sbprintln(&builder, "}")
	}
	fmt.sbprintln(&builder, "    result.core_color_tokens = {")
	for token in value.core_color_tokens {
		fmt.sbprintfln(&builder, "        alicorn.Style_Color_Token_ID({:d}),", u32(token))
	}
	fmt.sbprintln(&builder, "    }")

	fmt.sbprintfln(&builder, "    result.length_tokens = make([]alicorn.Style_Length, %d, allocator)", len(value.length_tokens))
	for length, index in value.length_tokens {
		fmt.sbprintf(&builder, "    result.length_tokens[{:d}] = alicorn.Style_Length{{logical_units=", index)
		fmt.sbprintf(&builder, "{:.9g}", length.logical_units)
		fmt.sbprintln(&builder, "}")
	}
	fmt.sbprintfln(&builder, "    result.extension_color_roles = make([]alicorn.Style_Extension_Color_Role_Binding, %d, allocator)", len(value.extension_color_roles))
	for binding, index in value.extension_color_roles {
		fmt.sbprintfln(&builder, "    result.extension_color_roles[{:d}] = alicorn.Style_Extension_Color_Role_Binding{{", index)
		fmt.sbprintfln(&builder, "        role=alicorn.Style_Extension_Color_Role_ID(u64({:d})),", u64(binding.role))
		fmt.sbprintfln(&builder, "        token=alicorn.Style_Color_Token_ID({:d}),", u32(binding.token))
		fmt.sbprintln(&builder, "    }")
	}
	fmt.sbprintfln(&builder, "    result.extension_length_roles = make([]alicorn.Style_Extension_Length_Role_Binding, %d, allocator)", len(value.extension_length_roles))
	for binding, index in value.extension_length_roles {
		fmt.sbprintfln(&builder, "    result.extension_length_roles[{:d}] = alicorn.Style_Extension_Length_Role_Binding{{", index)
		fmt.sbprintfln(&builder, "        role=alicorn.Style_Extension_Length_Role_ID(u64({:d})),", u64(binding.role))
		fmt.sbprintfln(&builder, "        token=alicorn.Style_Length_Token_ID({:d}),", u32(binding.token))
		fmt.sbprintln(&builder, "    }")
	}
	fmt.sbprintln(&builder, "    return result")
	fmt.sbprintln(&builder, "}")
	fmt.sbprintln(&builder, "")
	fmt.sbprintfln(&builder, "{:s}_destroy :: proc(value: ^alicorn.Style_Theme, allocator := context.allocator) {{", symbol)
	fmt.sbprintln(&builder, "    if value == nil { return }")
	fmt.sbprintln(&builder, "    delete(value.color_tokens, allocator)")
	fmt.sbprintln(&builder, "    delete(value.length_tokens, allocator)")
	fmt.sbprintln(&builder, "    delete(value.extension_color_roles, allocator)")
	fmt.sbprintln(&builder, "    delete(value.extension_length_roles, allocator)")
	fmt.sbprintln(&builder, "    value.color_tokens = nil")
	fmt.sbprintln(&builder, "    value.length_tokens = nil")
	fmt.sbprintln(&builder, "    value.extension_color_roles = nil")
	fmt.sbprintln(&builder, "    value.extension_length_roles = nil")
	fmt.sbprintln(&builder, "}")

	cloned, builder_clone_error := strings.clone(strings.to_string(builder))
	if builder_clone_error != nil { return "", false }
	generated = cloned
	return generated, true
}

theme_cli_codegen_identifier_is_valid :: proc(value: string) -> bool {
	if len(value) == 0 { return false }
	switch value {
	case "assert", "bit_field", "bit_set", "break", "case", "cast", "const",
	     "continue", "defer", "distinct", "do", "dynamic", "else", "enum",
	     "fallthrough", "false", "for", "foreign", "if", "import", "in",
	     "inline", "map", "maybe", "or_else", "or_return", "package", "proc",
	     "return", "select", "struct", "switch", "true", "typeid", "union",
	     "using", "when", "where", "while":
		return false
	}
	for index := 0; index < len(value); index += 1 {
		character := value[index]
		letter := character >= 'a' && character <= 'z' || character >= 'A' && character <= 'Z'
		if index == 0 {
			if !letter && character != '_' { return false }
		} else if !letter && (character < '0' || character > '9') && character != '_' {
			return false
		}
	}
	return true
}

// Odin import paths are emitted inside a quoted string. This intentionally
// accepts ordinary module/relative paths only, so the CLI never emits an
// unexpected escape or source fragment.
theme_cli_codegen_import_is_valid :: proc(value: string) -> bool {
	if len(value) == 0 { return false }
	for index := 0; index < len(value); index += 1 {
		character := value[index]
		letter := character >= 'a' && character <= 'z' || character >= 'A' && character <= 'Z'
		digit := character >= '0' && character <= '9'
		if !letter && !digit && character != '_' && character != '-' &&
		   character != '.' && character != '/' && character != ':' {
			return false
		}
	}
	return true
}
